### ISSUE TITLE
ModuleNotFoundError, Windows 11

### ISSUE THREAD

**Issue by AudioAnchorite** [TnS-hun/kobo-book-downloader#25]
```
C:\Users\user\kobo-book-downloader-master>python kobo-book-downloader list --help
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\user\kobo-book-downloader-master\kobo-book-downloader\__main__.py", line 1, in <module>
    from Commands import Commands
  File "C:\Users\user\kobo-book-downloader-master\kobo-book-downloader\Commands.py", line 2, in <module>
    from Kobo import Kobo, KoboException
  File "C:\Users\user\kobo-book-downloader-master\kobo-book-downloader\Kobo.py", line 17, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'
```
All commands result in this error. I have all dependencies installed properly (I use other scripts that depend on them--they are installed in the default location)

**Comment by TnS-hun** [comment]
Try installing pyreadline3 as a readline alternative on Windows.
`pip install pyreadline3`

After that it should work.
