### ISSUE TITLE
Error 401

### ISSUE THREAD

**Issue by fturco** [TnS-hun/kobo-book-downloader#9]
It seems kobo-book-downloader doesn't work anymore:

```
$ python kobo-book-downloader/kobo-book-downloader list
Refreshing expired authentication token
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "kobo-book-downloader/kobo-book-downloader/__main__.py", line 82, in <module>
    Main()
  File "kobo-book-downloader/kobo-book-downloader/__main__.py", line 66, in Main
    Initialize()
  File "kobo-book-downloader/kobo-book-downloader/__main__.py", line 15, in Initialize
    Globals.Kobo.LoadInitializationSettings()
  File "kobo-book-downloader/kobo-book-downloader/Kobo.py", line 133, in LoadInitializationSettings
    response = self.Session.get( "https://storeapi.kobo.com/v1/initialization", headers = headers, hooks = hooks )
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 653, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "kobo-book-downloader/kobo-book-downloader/Kobo.py", line 32, in ReauthenticationHook
    Globals.Kobo.RefreshAuthentication()
  File "kobo-book-downloader/kobo-book-downloader/Kobo.py", line 117, in RefreshAuthentication
    response.raise_for_status()
  File "/usr/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://storeapi.kobo.com/v1/auth/refresh
```

**Comment by fturco** [comment]
Oh... it seems kobo.com is currently down. I'll try again later.

**Comment by fturco** [comment]
Kobo is back again. Now kobo-book-downloader works fine. Sorry for the noise...
